coverage:
  range: 60..100
  status:
    project:
      default: off
      unit:
        target: 20%
        flags: unit
      instrumented:
        target: 20%
        flags: instrumented

flags:
  unit:
    paths:
      - app/src/main/io/github/wulkanowy
  instrumented:
    paths:
      - app/src/main/io/github/wulkanowy
