image: registry.gitlab.com/showcheap/android-ci:T25-B25.0.2

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assembleDebug
    - mv app/build/outputs/apk/app-debug.apk .
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}-${CI_BUILD_ID}"
    paths:
    - app-debug.apk

unitTests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
    - app/build/reports

functionalTests:
  stage: test
  script:
     - ./gradlew check
  artifacts:
    paths:
    - app/build/reports
